/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        action: {
          active: 'var(--color-action-active)',
          disabled: 'var(--color-action-disabled)',
          disabledBackground: 'var(--color-action-disabled-background)',
          focus: 'var(--color-action-focus)',
          hover: 'var(--color-action-hover)',
          selected: 'var(--color-action-selected)',
        },
        error: {
          contrast: 'var(--color-error-contrast)',
          DEFAULT: 'var(--color-error)',
          dark: 'var(--color-error-dark)',
          focusVisible: 'var(--color-error-focus-visible)',
          hover: 'var(--color-error-hover)',
          light: 'var(--color-error-light)',
          outlinedBorder: 'var(--color-error-outlined-border)',
          selected: 'var(--color-error-selected)',
        },
        info: {
          contrast: 'var(--color-info-contrast)',
          DEFAULT: 'var(--color-info)',
          dark: 'var(--color-info-dark)',
          focusVisible: 'var(--color-info-focus-visible)',
          hover: 'var(--color-info-hover)',
          light: 'var(--color-info-light)',
          outlinedBorder: 'var(--color-info-outlined-border)',
          selected: 'var(--color-info-selected)',
        },
        primary: {
          contrast: 'var(--color-primary-contrast)',
          dark: 'var(--color-primary-dark)',
          DEFAULT: 'var(--color-primary)',
          focus: 'var(--color-primary-focus)',
          focusVisible: 'var(--color-primary-focus-visible)',
          hover: 'var(--color-primary-hover)',
          light: 'var(--color-primary-light)',
          outlinedBorder: 'var(--color-primary-outlined-border)',
          selected: 'var(--color-primary-selected)',
        },
        secondary: {
          contrast: 'var(--color-secondary-contrast)',
          dark: 'var(--color-secondary-dark)',
          DEFAULT: 'var(--color-secondary)',
          focus: 'var(--color-secondary-focus)',
          focusVisible: 'var(--color-secondary-focus-visible)',
          light: 'var(--color-secondary-light)',
          hover: 'var(--color-secondary-hover)',
          outlinedBorder: 'var(--color-secondary-outlined-border)',
          selected: 'var(--color-secondary-selected)',
        },
        success: {
          contrast: 'var(--color-success-contrast)',
          DEFAULT: 'var(--color-success)',
          dark: 'var(--color-success-dark)',
          focusVisible: 'var(--color-success-focus-visible)',
          hover: 'var(--color-success-hover)',
          light: 'var(--color-success-light)',
          outlinedBorder: 'var(--color-success-outlined-border)',
          selected: 'var(--color-success-selected)',
        },
        text: {
          DEFAULT: 'var(--color-text-primary)',
          disabled: 'var(--color-text-disabled)',
          focus: 'var(--color-text-focus)',
          focusVisible: 'var(--color-text-focus-visible)',
          hover: 'var(--color-text-hover)',
          secondary: 'var(--color-text-secondary)',
          selected: 'var(--color-text-selected)',
        },
        warning: {
          contrast: 'var(--color-warning-contrast)',
          DEFAULT: 'var(--color-warning)',
          dark: 'var(--color-warning-dark)',
          focusVisible: 'var(--color-warning-focus-visible)',
          hover: 'var(--color-warning-hover)',
          light: 'var(--color-warning-light)',
          outlinedBorder: 'var(--color-warning-outlined-border)',
          selected: 'var(--color-warning-selected)',
        },
      },
      fontFamily: {
        base: [
          'Poppins',
          'Averta',
          'Inter var',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
    },
  },
  plugins: [],
};
